### ISSUE TITLE
Tips to debug 403 error?

### ISSUE THREAD

**Issue by Nomad-Go** [aws-samples/amazon-quicksight-embedding-sample#2]
I successfully retrieve my embed URL from my lambda function. What is weird is that I can embed some of my dashboards but I get a 403 error on other dashboards.

Is there a piece I'm missing? How should I configure the "share" permissions on the QuickSight dashboard?

**Comment by ajkulkarni** [comment]
You could login to your QuickSight dashboard and go to Share -> Share dashboard. Either search for the Cognito users individually or share the dashboard with all users (checkbox).

**Comment by Nomad-Go** [comment]
Thank you the share with all users worked for a development dashboard I have. I would rather add user individually. 

My Cognito User pool is configured to allow use of the email as the username. In this case Cognito is assigning a long uuid for a users username. I took the first few characters of this uuid and started typing them into the search box when adding users to a dashboard. They are not appearing in the auto complete.

When I go to Manage Quicksight -> Manage Users from the Quicksight dashboard I see a few users listed in the form of `quicksight-embed-cognito-res-CognitoAuthorizedRole-(clipped off because I can't adjust the column widths)`. I guess this starts to highlight my misunderstanding of this set up.

Does each new Cognito user automatically get a 'User' profile in Quicksight? I thought Cognito users were assuming a role that was then granted permissions to access a dashboard for a given amount of time? Does quicksight pull in users from iAM and create a seperate DB of users? I'm confused how Quicksight manages users in general.

**Comment by ajkulkarni** [comment]
Sorry for the delay in response. For the first part of your question, in the username you could replace the uuid with email. Check this code snippet: https://github.com/aws-samples/amazon-quicksight-embedding-sample/blob/master/lambda/index.js#L101. Here, we explicitly set the session name as `result.getIdToken().payload.sub`, which is the uuid. You could replace `sub` with Cognito username or the email, look at structure for the payload object for the exact fields to use: https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html

For the second part, yes, we register a new QuickSight reader corresponding to the Cognito user who visits the embedded dashboard.
