### ISSUE TITLE
502 Error

### ISSUE THREAD

**Issue by hobot43** [aws-samples/amazon-quicksight-embedding-sample#3]
I think I've set this all up according to the instructions, and my user account can retreive session info from the aws cognito-idp admin-initiate-auth command, but whenever I test the API in Gateway, I get a 502 error.

I've tried testing the lambda function directly and get:
2019-02-21T16:57:20.679Z	430b1cf7-15a2-4f58-a6e3-c1ec25f00e92	(node:1) UnhandledPromiseRejectionWarning: ReferenceError: alert is not defined
    at Object.onFailure (/var/task/index.js:185:13)
    at /var/task/node_modules/amazon-cognito-identity-js/lib/CognitoUser.js:331:27
    at /var/task/node_modules/amazon-cognito-identity-js/lib/Client.js:96:18
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)

**Comment by ajkulkarni** [comment]
Can you check if the Cognito user is confirmed?

**Comment by hobot43** [comment]
The user is definitely confirmed in Cognito

**Comment by ajkulkarni** [comment]
Line number 185 in the lambda/index.js is something we should change, I will do that shortly. For now can you replace the alert with:

`console.log(err, err.stack);`
`callback(err);`

This will tell us what's wrong. Can you reply back with the error stack you get after adding this?

**Comment by hobot43** [comment]
There we go, I should have noticed that it wasn't throwing the actual error output.  Once I could see it, I got it fixed (I had an extra space at the end of my ClientID, of all the dumb things).

Thanks for your help.

**Comment by ajkulkarni** [comment]
Always happy to help! Glad you found it!
