### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present

### ISSUE THREAD

**Issue by CoolR7** [aws-samples/amazon-quicksight-embedding-sample#7]
Hi

I am using Angular for embedding the dashboard. I have used the index js code from this sample . When I am trying to register the assume role user as a quickisght user.

I am getting the below error

zone.js:3243 OPTIONS https://quicksight.us-east-1.amazonaws.com/accounts/000000000/namespaces/default/users 403
bbef8678.ngrok.io/:1 Access to XMLHttpRequest at 'https://quicksight.us-east-1.amazonaws.com/accounts/00000000/namespaces/default/users' from origin 'https://bbef8643.ngrok.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Could you please help me with this error?

**Comment by Senneseph** [comment]
@CoolR7 

Could you elaborate on how you're embedding the URL?  I've been unable to find any information on QuickSight + Angular (or other SPA frameworks).  I've generated the URL and I can assign it to an iframe's src attribute and the dashboard does embed.  But I'm not sure if I'm missing out on functionality provided through the javascript SDK.
