### ISSUE TITLE
Access to 'https://<removed>.cloudfront.net/embed-dashboard.bundle.df397614c8bc1dae4be8.14.js' from origin 'https://us-east-1.quicksight.aws.amazon.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by mcsf13m036** [aws-samples/amazon-quicksight-embedding-sample#8]
I am using S3 hosting with CloudFront distribution and listed the CloudFront URL in QuickSight domain. When using sample code i am seeing error:
**Access to 'https://<removed>.cloudfront.net/embed-dashboard.bundle.df397614c8bc1dae4be8.14.js' from origin 'https://us-east-1.quicksight.aws.amazon.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource**

Below is my CloudFront setting:
Origin Custom header:
                   Access-Control-Allow-Origin: https://<removed>.cloudfront.net
Allowed HTTP methods:
                  GET, HEAD, OPTIONS
Whitelisted headers:
                  Access-Control-Request-Headers
                  Access-Control-Request-Method
                  Origin

kindly guide.

**Comment by cherukum-Amazon** [comment]
Would you go through AWS Cloud support and raise a support ticket to the QuickSight team. The question looks unrelated to the sample code and specific to your cloud front setup. We can dive deep and investigate to get to a resolution through support channel.

**Comment by AndrewCi** [comment]
Experiencing this same issue. Was this resolved?

**Comment by philipasp** [comment]
I am also experiencing the same issue. Any resolution and guidance?

**Comment by lukec** [comment]
I am also experiencing this same issue. Any advice?
